# Generated by Django 4.0.1 on 2023-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cart_member', models.CharField(max_length=15)),
                ('cart_prod', models.CharField(max_length=10)),
                ('cart_qty', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lprod',
            fields=[
                ('lprod_gu', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lprod_id', models.IntegerField()),
                ('lprod_nm', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'lprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_add1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_lgu', models.CharField(max_length=4)),
                ('prod_cost', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('prod_sale', models.IntegerField()),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
