# Generated by Django 4.0.1 on 2023-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0002_cartmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMemberProd',
            fields=[
                ('cart_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cart_qty', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
