# Generated by Django 4.0.1 on 2023-07-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0003_cartmemberprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdLprod',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_cost', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('prod_sale', models.IntegerField()),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
